platform:
  - x64

environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  - git submodule update --init --recursive
  - ps: Install-Product node $env:nodejs_version
  - yarn install

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

build_script:
  - npm run publish

test: off